// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aurocCPP
double aurocCPP(NumericVector score, LogicalVector boolVect, double n1, double n2);
RcppExport SEXP _oob_aurocCPP(SEXP scoreSEXP, SEXP boolVectSEXP, SEXP n1SEXP, SEXP n2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type boolVect(boolVectSEXP);
    Rcpp::traits::input_parameter< double >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< double >::type n2(n2SEXP);
    rcpp_result_gen = Rcpp::wrap(aurocCPP(score, boolVect, n1, n2));
    return rcpp_result_gen;
END_RCPP
}
// pvalLmFit
NumericVector pvalLmFit(arma::vec residuals, NumericVector coefficients, int p, arma::mat qr);
RcppExport SEXP _oob_pvalLmFit(SEXP residualsSEXP, SEXP coefficientsSEXP, SEXP pSEXP, SEXP qrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type qr(qrSEXP);
    rcpp_result_gen = Rcpp::wrap(pvalLmFit(residuals, coefficients, p, qr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_oob_aurocCPP", (DL_FUNC) &_oob_aurocCPP, 4},
    {"_oob_pvalLmFit", (DL_FUNC) &_oob_pvalLmFit, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_oob(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
