# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aurocCPP <- function(score, boolVect, n1, n2) {
    .Call(`_oob_aurocCPP`, score, boolVect, n1, n2)
}

pvalLmFit <- function(residuals, coefficients, p, qr) {
    .Call(`_oob_pvalLmFit`, residuals, coefficients, p, qr)
}

